import { LANGUAGE_PACK_SCHEMA, type LanguagePack } from "../localization.ts";

export const englishLanguagePack: LanguagePack = {
  schema: LANGUAGE_PACK_SCHEMA,
  locale: "en-US",
  englishName: "English (United States)",
  nativeName: "English (United States)",
  direction: "ltr",
  version: "0.1.0",
  messages: {
    "app.brand.tagline": "Tools for public health practice",
    "menu.file.label": "File",
    "menu.view.label": "View",
    "menu.tools.label": "Tools",
    "menu.help.label": "Help",
    "menu.tools.options": "Options...",
    "menu.statcalc.label": "StatCalc",
    "options.language.heading": "Language",
    "options.title": "Options",
    "options.language.description": "Choose the language used for application menus and messages.",
    "options.language.label": "Application language",
    "options.language.englishFallback": "English remains available as the fallback language. Program commands, field names, coded values, and stored data are not translated.",
    "options.language.restart": "Language changes apply immediately where supported. Some legacy surfaces may require reopening.",
    "options.language.pseudoNote": "Pseudo (accented test) expands text to reveal clipping and untranslated interface strings. It is not a user language.",
    "options.language.saved": "Language preference saved in this browser.",
    "common.apply": "Apply",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "main.createForms": "Create Forms",
    "main.enterData": "Enter Data",
    "main.analyzeData": "Analyze Data",
    "main.classic": "Classic",
    "main.visualDashboard": "Visual Dashboard",
    "main.createMaps": "Create Maps",
    "status.records.count": "{count} records",
  },
};
